version: '3.8'
services:
  platex-samba:
    build: .
    container_name: platex-samba
    environment:
      - SMB_PASSWORD=smbpass
    ports:
      # Use high-numbered host ports to avoid Windows local SMB service conflicts
      - "1139:139"
      - "1445:445"
    volumes:
      - ./share:/srv/samba/share
      - ./volume:/usr/local/texlive
    restart: unless-stopped
