version: '3.8'
services:
  platex-samba:
    build: .
    container_name: platex-samba
    environment:
      - SMB_PASSWORD=smbpass
    # Port publishing removed because many Windows hosts already use port 445/139.
    # If you run this on a Linux host or a VM where ports are free, you can add:
    #   - "139:139"
    #   - "445:445"
    volumes:
      - ./share:/srv/samba/share
      - ./volume:/usr/local/texlive
    restart: unless-stopped
